Register to community
Corporate-Jargon/Mxer pull request #24
Opened 2022-11-16 01:59 UTC by eleferrets

The register to community stuff is not finished because it needs the finished site and navbar, but this is a way to get the base version everyone should have.

2022-11-16 18:26 UTC, jz575 requested changes
once Michael's PR is approved **pull** and
move code from
- LoginActivity.kt to LoginFragment.kt
- RegisterActivity.kt to RegisterFragment.kt
delete
- activity_login.xml
- activity_register.xml
make sure fragments refer to the proper xml
edit from existing strings.xml

2022-11-16 23:24 UTC, eleferrets commented
> once Michael's PR is approved **pull** and move code from
> 
> * LoginActivity.kt to LoginFragment.kt
> * RegisterActivity.kt to RegisterFragment.kt
>   delete
> * activity_login.xml
> * activity_register.xml
>   make sure fragments refer to the proper xml
>   edit from existing strings.xml

The intents would not work for the fragments without them being activities like in parstagram. The fragments were not needed for the main screens like login or register, only places where the bottom navigation bar was used.

2022-11-17 02:39 UTC, jz575 approved these changes

2022-11-17 13:44 UTC, so-michael approved these changes

2022-11-17 15:08 UTC, merged