Edit bio
Corporate-Jargon/Mxer pull request #40
Opened 2022-12-03 21:25 UTC by so-michael

also some code cleanup

2022-12-03 21:59 UTC, eleferrets requested changes
It would be better to show the updated bio after changing it in parse.
Also, if I have a bio already in parse, it doesn't show up at all

2022-12-03 22:01 UTC, Strevia requested changes
Small thing but it might be slightly better practice for setBio to take a parameter rather than using the global variable

2022-12-04 22:45 UTC, Strevia approved these changes

2022-12-04 23:11 UTC, eleferrets approved these changes

2022-12-04 23:36 UTC, merged