Compose community
Corporate-Jargon/Mxer pull request #41
Opened 2022-12-05 15:35 UTC by jz575

2022-12-05 17:15 UTC, eleferrets requested changes
Relative time does not show up
![Screenshot 2022-12-05 121340](https://user-images.githubusercontent.com/40572853/205700178-70184245-250e-4241-b876-22c8c90ac8a6.png)
Compose post *can* be called 'compose comment' if they aren't sharing the same fragment, unless we want to consider comments as posts

2022-12-06 01:42 UTC, eleferrets approved these changes

2022-12-06 01:43 UTC, eleferrets approved these changes

2022-12-06 01:44 UTC, Strevia approved these changes

2022-12-06 01:45 UTC, merged